/// Keys into `Localizable.strings` (en / zh-Hans).
enum LocalizationKey: String {
    case settings = "settings.title"
    case refresh = "menu.refresh"
    case quit = "menu.quit"
    case quotaTooltip = "quota.tooltip"
    case errorPrefix = "error.prefix"
    case refreshFailedPrefix = "refresh.failed.prefix"

    case fiveHourTitle = "quota.window.fiveHour"
    case weeklyTitle = "quota.window.weekly"
    case mimoTokenPlanTitle = "quota.window.mimoTokenPlan"
    case remaining = "quota.remaining"
    case reset = "quota.reset"
    case noData = "quota.window.noData"
    case resetCreditsSuffix = "quota.resetCredits.suffix"

    case proxy = "settings.tab.proxy"
    case hotkey = "settings.tab.hotkey"
    case language = "settings.tab.language"
    case providers = "settings.tab.providers"
    case about = "settings.tab.about"
    case save = "settings.button.save"
    case cancel = "settings.button.cancel"
    case appVersion = "settings.app.version"
    case aboutSubtitle = "settings.about.subtitle"
    case aboutFeedback = "settings.about.feedback"
    case aboutGitHub = "settings.about.github"

    case proxySubtitle = "settings.proxy.subtitle"
    case proxyMode = "settings.proxy.mode"
    case proxyAddress = "settings.proxy.address"
    case proxyManualHelp = "settings.proxy.manualHelp"
    case proxyAutomaticHelp = "settings.proxy.automaticHelp"
    case proxyModeAutomatic = "settings.proxy.mode.automatic"
    case proxyModeManual = "settings.proxy.mode.manual"
    case proxyModeDisabled = "settings.proxy.mode.disabled"

    case hotkeySubtitle = "settings.hotkey.subtitle"
    case enableGlobalHotkey = "settings.hotkey.enable"
    case openMenu = "settings.hotkey.openMenu"
    case pressHotkey = "settings.hotkey.press"
    case clickToRecordHotkey = "settings.hotkey.record"

    case languageSubtitle = "settings.language.subtitle"
    case languagePreferenceSystem = "settings.language.system"
    case languagePreferenceEnglish = "settings.language.english"
    case languagePreferenceSimplifiedChinese = "settings.language.simplifiedChinese"

    case providersSubtitle = "settings.providers.subtitle"
    case providersHelp = "settings.providers.help"
    case providersSelectedCount = "settings.providers.selectedCount"
    case providersDragHint = "settings.providers.dragHint"

    case invalidProxyTitle = "validation.proxy.title"
    case invalidProxyMessage = "validation.proxy.message"
    case invalidHotkeyTitle = "validation.hotkey.title"
    case invalidHotkeyMessage = "validation.hotkey.message"

    case notificationPermissionTitle = "notification.permission.title"
    case notificationPermissionMessage = "notification.permission.message"
    case openSystemSettings = "notification.permission.openSettings"
    case later = "notification.permission.later"

    case codexBinaryMissing = "error.codexBinaryMissing"
    case missingRateLimitWindow = "error.missingRateLimitWindow"
    case invalidResponse = "error.invalidResponse"
    case requestTimedOut = "error.requestTimedOut"
    case grokUnauthorized = "error.grokUnauthorized"
    case grokNotSignedIn = "error.grokNotSignedIn"
    case grokRequestFailed = "error.grokRequestFailed"
    case claudeUnauthorized = "error.claudeUnauthorized"
    case claudeNotSignedIn = "error.claudeNotSignedIn"
    case claudeTokenExpired = "error.claudeTokenExpired"
    case claudeRequestFailed = "error.claudeRequestFailed"
    case mimoCodeNotSignedIn = "error.mimoCodeNotSignedIn"
    case mimoCodeInvalidAuth = "error.mimoCodeInvalidAuth"
    case mimoCookieMissing = "error.mimoCookieMissing"
    case mimoUnauthorized = "error.mimoUnauthorized"
    case mimoRequestFailed = "error.mimoRequestFailed"
    case mimoKeychainWriteFailed = "error.mimoKeychainWriteFailed"

    case mimoCookieLabel = "settings.providers.mimoCookie.label"
    case mimoCookiePlaceholder = "settings.providers.mimoCookie.placeholder"
    case mimoCookieHelp = "settings.providers.mimoCookie.help"
    case mimoCookieSaveErrorTitle = "settings.providers.mimoCookie.saveErrorTitle"

    case severityWarning = "notification.severity.warning"
    case severityUrgent = "notification.severity.urgent"
    case severityCritical = "notification.severity.critical"

    case lowQuotaTitle = "notification.lowQuota.title"
    case lowQuotaBody = "notification.lowQuota.body"
    case lowQuotaBodyWithReset = "notification.lowQuota.bodyWithReset"
}
